### PR TITLE
install_doc

### PR DESCRIPTION
**Pull request by alighaleb1**
The install document includes an explanation of how to download and install XAMPP for others to understand how to get our project/website to run.

### CODE REVIEW

**Comment by JoshBrink** [comment]
Great job! The install document will be very helpful for people to get familiar with our software.

**Comment by etracht** [comment]
Awesome job Ali! Good job in including pictures. Very helpful to those who are virtual learners.

**Comment by JonathanNemchak** [comment]
Great work! Nice and simple for anyone to follow.

**Comment by DylanBerquist** [comment]
Thanks Ali, this is a very helpful step-by-step guide!

**Comment by Rghaleb** [comment]
Good jab Ali, useful and simple explanation.

**Pull request merged**
