### PR TITLE
Emily.tracht organizing project files

### PR DESCRIPTION
**Pull request by etracht**
Organized the projec to follow PHP and github project standards.
PHP project standard used here: https://github.com/php-pds/skeleton

- Added a README to every folder
- Created separate folders for images, src, includes, HTML, PHP, and css
- added a LICENSE.LIC file
- added a .gitignore file
- added a CHANGELOG file
- created a test folder for code
- created a public folder for web server code

### CODE REVIEW

**Comment by JoshBrink** [comment]
Great work! Thank you for adding all of these changes to organize the git repository! Explanation of a folder: The PHP folder will include all PHP versions of our webpages, including a config file and functions.

**Comment by YaozeZ** [comment]
OK, thank you

**Comment by YaozeZ** [comment]
You did a great job. Thank you.
.gitignore file: In Git, there is a special file whose full name is .gitignore. This file can be opened with TXT. The main function of this file is to block certain files so that they are not tracked and pushed so that they are not uploaded to GitHub or other platforms.

**Comment by alighaleb1** [comment]
Thanks for organizing everything! the images folder will contain all the images used in our website.

**Comment by Rghaleb** [comment]
Good jab Emliy! Thank you.
The css folder will contain the css files needed to style our web page.

**Comment by sjiang1** [comment]
> Good jab Emliy! Thank you.
> The css folder will contain the css files needed to style our web page.

Hello! I didn't find a css folder in the repository! @etracht @Rghaleb

**Comment by JonathanNemchak** [comment]
Looks much better now, The images folder is the folder for all the images on website to be in one spot so they are easy to find and locate.

**Comment by DylanBerquist** [comment]
Finding will be a lot more convenient with everything organized correctly. Thanks for doing this for the group, Emily. The PHP folder is the folder that holds all the PHP files for our project.

**Pull request merged**
